repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    - id: end-of-file-fixer
    - id: trailing-whitespace
  - hooks:
      - id: black
        exclude: test_mypy\.py$ # https://github.com/davidfritzsche/pytest-mypy-testing/issues/29
        language_version: python3
    repo: https://github.com/psf/black
    rev: 26.1.0
  - hooks:
      - id: isort
        language_version: python3
    repo: https://github.com/timothycrosley/isort
    rev: 7.0.0
  - hooks:
      - id: flake8
        language_version: python3
        additional_dependencies:
          - flake8-bugbear
          - flake8-comprehensions
          - flake8-debugger
    repo: https://github.com/pycqa/flake8
    rev: 7.3.0
  - repo: https://github.com/adamchainz/blacken-docs
    rev: 1.20.0
    hooks:
      - id: blacken-docs
        additional_dependencies:
          - black==26.1.0
  - repo: local
    hooks:
      - id: no-colon-comments
        name: "No Sphinx-style #: comments"
        entry: python pre-commit-scripts/no_colon_comments.py
        language: system
        types: [python]
        files: ^zyte_common_items/.*\.py$
  - repo: https://github.com/sphinx-contrib/sphinx-lint
    rev: v1.0.2
    hooks:
      - id: sphinx-lint
  - repo: https://github.com/rhysd/actionlint
    rev: v1.7.11
    hooks:
      - id: actionlint
