[tox]
min_version = 4.20
envlist = min,min-extra,py311,py312,py313,py314,extra,mypy,docs,twinecheck

[base]
deps =
    packaging
    pytest>=9
    pytest-asyncio
    pytest-cov>=7
    pytest-mypy-testing==0.2.0

[testenv]
deps =
    {[base]deps}
commands =
    pytest \
        --cov-report=term-missing:skip-covered \
        --cov-report= \
        --cov-report=xml \
        --cov=zyte_common_items \
        {posargs:zyte_common_items docs tests}


[testenv:min]
basepython = python3.11
deps =
    {[base]deps}
    attrs==22.2.0
    clear-html==0.4.0
    itemadapter==0.8.0
    Jinja2==2.10.2
    # Pin markupsafe for Jinja2
    markupsafe==1.1.1
    # Newer mypy requires newer typing-extensions
    mypy==1.10.1
    price-parser==0.3.4
    typing-extensions==4.5.0
    web-poet==0.14.0
    zyte-parsers==0.5.0

[testenv:extra]
deps =
    {[base]deps}
    scrapy
commands =
    pytest \
        --cov-report=term-missing:skip-covered \
        --cov-report= \
        --cov-report=xml \
        --cov=zyte_common_items \
        --doctest-glob="*.rst" \
        --doctest-modules \
        {posargs:zyte_common_items docs tests}

[testenv:min-extra]
basepython = python3.11
deps =
    {[testenv:min]deps}
    scrapy==2.7.0
    # w3lib 2.5.0 breaks Scrapy < 2.13.0, pin it to oldest supported by web-poet 0.14.0
    w3lib==1.22.0

[testenv:docs]
changedir = docs
deps =
    -rdocs/requirements.txt
setenv =
    READTHEDOCS_PROJECT=zyte-common-items
    READTHEDOCS_VERSION=main
commands =
    sphinx-build -n -b html . {envtmpdir}/html
    # Temporarily removed -W due to
    # https://github.com/scrapinghub/web-poet/pull/194

[testenv:mypy]
deps =
    mypy==2.4.0
    clear-html==0.5.0
    price-parser==0.5.1
    pytest==9.1.1
    Scrapy==2.19.0
    types-lxml==2026.2.16
    zyte-parsers==0.6.0

commands = mypy zyte_common_items tests

[testenv:twinecheck]
deps =
    twine==7.0.0
    build==1.6.1
commands =
    python -m build --sdist
    twine check dist/*

[testenv:linters]
deps =
    pre-commit
commands = pre-commit run --all-files --show-diff-on-failure
